### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by HonzaCuhel**
This PR includes:
- unit tests for used components
- integration tests for the whole pipeline
- workflow for automatic testing when creating PRs

### CODE REVIEW

**Review by sokovninn — COMMENTED** [review]
@HonzaCuhel thanks a lot for the tests. @tersekmatija, should we set some kind of test coverage threshold for future PRs?

**Comment by sokovninn** [comment]
BTW, I don't see check results for this PR. @HonzaCuhel are they skipped?

**Comment by HonzaCuhel** [comment]
> BTW, I don't see check results for this PR. @HonzaCuhel are they skipped?

They weren't skipped, but for some reason, there are not visible now. So I'm linking here the results:
- the pre-commit check [link](https://github.com/luxonis/datadreamer/actions/runs/7513265501)
- the actual tests [link](https://github.com/luxonis/datadreamer/actions/runs/7513265500)

I had to set some skipping rules for HW requirements for most of the tests, since a lot of them were failing on the standard GH runners. [Here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) are the specs of the standard GH runners, which are for free. The biggest issue is the disk size, there's only 14GB, which is just not enough for all the models and the dependencies, therefore I wasn't not even able to run the unittests for image generation. 
image

Apparently, there are also GH large runners that are only available for organizations and enterprises using the GitHub Team or GitHub Enterprise Cloud plans ([link](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#machine-specs-for-larger-runners)). Or we could run the tests on our device.

**Comment by sokovninn** [comment]
@tersekmatija @kozlov721 Your thoughts on running resource-intensive tests?

**Pull request merged**
